# Generated by Django 5.1 on 2024-11-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
