# Generated by Django 5.1 on 2024-11-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_alter_entry_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='Transaction',
        ),
    ]
